### ISSUE TITLE
Button - rodzaje przycisków

### ISSUE THREAD

**Issue by martab0** [asiakostrzewa/ShazamDesignSystem#11]
https://asiakostrzewa.github.io/ShazamDesignSystem/docs/Components.html#button
Nie rozumiem logiki, wg jakiej niektóre przyciski są na obrazku (for light Apple system mode, for dark Apple system mode), a inne są opisane poniżej. Dałoby radę to jakoś objaśnić?

**Comment by asiakostrzewa** [comment]
Hm... racja. Mogło to być trochę chaotyczne. Zaproponowałam inne rozwiązanie. Zobacz proszę, czy teraz jest w porządku. 
Chodzi o pokazanie, jakie kombinacje kolorystyczne (w zależności od light/dark mode) są dopuszczalne dla przycisków, kiedy masz do dyspozycji:
- tylko ikonę,
- tylko tekst,
- tekst wraz z ikoną. 

Opis przycisków poniżej (Forward button, More button etc.) ma już zastosowanie dla obydwóch trybów systemowych (zarówno dark, jak i light).

**Comment by martab0** [comment]
Opis przycisków poniżej (Forward button, More button etc.) ma już zastosowanie dla obydwóch trybów systemowych (zarówno dark, jak i light) - tej informacji brakuje!!!

**Comment by asiakostrzewa** [comment]
Informacje dodane 👍
