### ISSUE TITLE
Who are we?

### ISSUE THREAD

**Issue by martab0** [asiakostrzewa/ShazamDesignSystem#3]
Zastanawiam się nad "we" na stronach Branding i Components. Czy to celowy zabieg, żeby dokumentacja wyglądała jakby pisał Shazam?

**Comment by asiakostrzewa** [comment]
Dokładnie tak. Założyłam, że personą jest pracownik Shazam, stąd "we" oraz "our".

**Comment by martab0** [comment]
Rozumiem! Myślę, że dobrze będzie to albo ująć na stronie głównej, albo wyjaśnić na obronie.

**Comment by asiakostrzewa** [comment]
Dobrze. Objaśnię to na obronie w sekcji dotyczącej persony 👍
