### ISSUE TITLE
Case-sensitive

### ISSUE THREAD

**Issue by martab0** [asiakostrzewa/ShazamDesignSystem#5]
https://asiakostrzewa.github.io/ShazamDesignSystem/docs/Branding.html#letter-case-
Co to znaczy: "Make all titles, headings and components (such as labels or buttons) case-sensitive"?

https://asiakostrzewa.github.io/ShazamDesignSystem/docs/Branding.html#titles-and-headings-
Co to znaczy: "Be case-sensitive in titles and headings"?

**Comment by asiakostrzewa** [comment]
W obydwóch przypadkach chodzi o to, żeby UX Designerzy dbali o poprawny zapis tytułów, nagłówków, czy przycisków - to znaczy, aby zapisywali je rozpoczynając nazwy od wielkiej litery.

**Comment by martab0** [comment]
Proponuję napisać, co dokładnie trzeba robić przy odnoszeniu się do tytułów, nagłówków, czy przycisków.

"Refer to titles, headings, buttons and other screen options starting with a capital letter"? (robocza wersja łopatologiczna)

**Comment by asiakostrzewa** [comment]
Dobrze. Poprawiłam w obydwóch miejscach 👍
