### ISSUE TITLE
Dates

### ISSUE THREAD

**Issue by martab0** [asiakostrzewa/ShazamDesignSystem#8]
Czy sekcja o datach jest celowo powtórzona w rozdziałach Branding i Components? Jeśli tak, to do rozdziału Components proponuję te same poprawki, jakie podałam dla sekcji Branding.

**Comment by asiakostrzewa** [comment]
Dokładnie tak - jest to zabieg celowy. W sekcji Branding chodzi tylko o pokazanie zasad pod kątem "gramatycznym", natomiast w sekcji Components rozdział Dates jest rozszerzony o szczegóły dotyczące zapisu oraz podałam tam graficzny przykład.
Oczywiście, naniosę poprawki również w sekcji Components.
